/**
 * PDF Generation utilities
 * Uses browser-based PDF generation for reports, certificates, and invoices
 */

/**
 * Generate a student progress report as HTML (to be printed as PDF)
 */
export function generateProgressReportHTML(data: {
  studentName: string;
  studentId: string;
  age: string;
  iscedLevel: string;
  classroom: string;
  period: string;
  domains: Array<{
    name: string;
    score: number;
    status: string;
    notes: string;
  }>;
  milestones: Array<{
    title: string;
    status: string;
    date: string;
  }>;
  teacherNotes: string;
  schoolName: string;
  schoolLogo?: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', Arial, sans-serif; color: #1a1a2e; line-height: 1.6; padding: 40px; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 3px solid #4299e1; padding-bottom: 20px; }
    .header h1 { color: #4299e1; font-size: 28px; }
    .header h2 { color: #666; font-size: 16px; margin-top: 5px; }
    .student-info { display: flex; justify-content: space-between; margin: 20px 0; padding: 15px; background: #f7fafc; border-radius: 8px; }
    .student-info div { }
    .student-info label { font-size: 12px; color: #666; display: block; }
    .student-info span { font-weight: 600; font-size: 14px; }
    .section { margin: 25px 0; }
    .section h3 { font-size: 18px; color: #4299e1; margin-bottom: 15px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; }
    .domain-row { display: flex; align-items: center; margin: 10px 0; padding: 10px; background: #f7fafc; border-radius: 8px; }
    .domain-name { width: 200px; font-weight: 600; font-size: 14px; }
    .progress-bar { flex: 1; height: 20px; background: #e2e8f0; border-radius: 10px; overflow: hidden; margin: 0 15px; }
    .progress-fill { height: 100%; border-radius: 10px; }
    .progress-fill.excellent { background: #48bb78; }
    .progress-fill.good { background: #4299e1; }
    .progress-fill.attention { background: #ecc94b; }
    .progress-fill.delayed { background: #f56565; }
    .score { font-weight: 700; width: 50px; text-align: right; }
    .milestone-list { list-style: none; }
    .milestone-list li { padding: 8px 12px; margin: 5px 0; background: #f7fafc; border-radius: 8px; display: flex; justify-content: space-between; }
    .milestone-status { font-size: 12px; padding: 2px 8px; border-radius: 12px; font-weight: 600; }
    .milestone-status.achieved { background: #c6f6d5; color: #276749; }
    .milestone-status.in-progress { background: #bee3f8; color: #2a4365; }
    .notes { padding: 15px; background: #ebf8ff; border-radius: 8px; border-left: 4px solid #4299e1; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #666; font-size: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${data.schoolName}</h1>
    <h2>Student Development Progress Report</h2>
    <p style="color: #888; margin-top: 5px;">Report Period: ${data.period}</p>
  </div>

  <div class="student-info">
    <div><label>Student Name</label><span>${data.studentName}</span></div>
    <div><label>Student ID</label><span>${data.studentId}</span></div>
    <div><label>Age</label><span>${data.age}</span></div>
    <div><label>Program</label><span>${data.iscedLevel}</span></div>
    <div><label>Classroom</label><span>${data.classroom}</span></div>
  </div>

  <div class="section">
    <h3>Development Domains</h3>
    ${data.domains
      .map(
        (d) => `
      <div class="domain-row">
        <div class="domain-name">${d.name}</div>
        <div class="progress-bar">
          <div class="progress-fill ${d.score >= 80 ? "excellent" : d.score >= 60 ? "good" : d.score >= 40 ? "attention" : "delayed"}" style="width: ${d.score}%"></div>
        </div>
        <div class="score">${d.score}%</div>
      </div>
    `
      )
      .join("")}
  </div>

  <div class="section">
    <h3>Milestones</h3>
    <ul class="milestone-list">
      ${data.milestones
        .map(
          (m) => `
        <li>
          <span>${m.title} <small style="color: #888">(${m.date})</small></span>
          <span class="milestone-status ${m.status === "ACHIEVED" ? "achieved" : "in-progress"}">
            ${m.status === "ACHIEVED" ? "Achieved" : "In Progress"}
          </span>
        </li>
      `
        )
        .join("")}
    </ul>
  </div>

  <div class="section">
    <h3>Teacher Notes</h3>
    <div class="notes">${data.teacherNotes}</div>
  </div>

  <div class="footer">
    <p>Generated on ${new Date().toLocaleDateString()} | ${data.schoolName}</p>
    <p>This report is generated by EduPlatform - Educational Management System</p>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate a certificate HTML
 */
export function generateCertificateHTML(data: {
  studentName: string;
  programName: string;
  schoolName: string;
  issuedDate: string;
  achievements: string[];
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', serif; }
    .certificate { width: 800px; min-height: 600px; margin: 0 auto; padding: 60px; text-align: center; border: 12px solid #4299e1; position: relative; background: linear-gradient(135deg, #fff 0%, #f7fafc 100%); }
    .certificate::before { content: ''; position: absolute; top: 8px; left: 8px; right: 8px; bottom: 8px; border: 2px solid #4299e1; }
    .title { font-size: 36px; color: #4299e1; margin: 20px 0 10px; letter-spacing: 4px; text-transform: uppercase; }
    .subtitle { font-size: 16px; color: #666; margin-bottom: 30px; }
    .student-name { font-size: 42px; color: #1a1a2e; font-style: italic; margin: 20px 0; border-bottom: 2px solid #4299e1; display: inline-block; padding-bottom: 5px; }
    .program { font-size: 18px; color: #444; margin: 15px 0; }
    .achievements { margin: 20px auto; max-width: 500px; text-align: left; }
    .achievements li { margin: 5px 0; color: #444; }
    .date { margin-top: 30px; color: #666; font-size: 14px; }
    .signature { margin-top: 40px; display: flex; justify-content: space-around; }
    .signature div { text-align: center; }
    .signature-line { width: 200px; border-top: 1px solid #333; margin-top: 40px; padding-top: 5px; font-size: 12px; color: #666; }
    @media print { .certificate { border: 12px solid #4299e1; } }
  </style>
</head>
<body>
  <div class="certificate">
    <div style="font-size: 24px; color: #4299e1;">&#9733;</div>
    <div class="title">Certificate</div>
    <div class="subtitle">of Achievement</div>
    <p>This is to certify that</p>
    <div class="student-name">${data.studentName}</div>
    <div class="program">Has successfully completed the<br><strong>${data.programName}</strong><br>at ${data.schoolName}</div>
    ${data.achievements.length > 0 ? `
      <div class="achievements">
        <p style="font-weight: bold; text-align: center; margin-bottom: 10px;">Key Achievements:</p>
        <ul>${data.achievements.map((a) => `<li>${a}</li>`).join("")}</ul>
      </div>
    ` : ""}
    <div class="date">Issued on ${data.issuedDate}</div>
    <div class="signature">
      <div>
        <div class="signature-line">School Principal</div>
      </div>
      <div>
        <div class="signature-line">Lead Teacher</div>
      </div>
    </div>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Generate invoice HTML
 */
export function generateInvoiceHTML(data: {
  invoiceNumber: string;
  studentName: string;
  studentId: string;
  schoolName: string;
  items: Array<{ description: string; amount: number }>;
  total: number;
  dueDate: string;
  issuedDate: string;
  status: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', Arial, sans-serif; color: #1a1a2e; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 30px; }
    .header h1 { color: #4299e1; font-size: 28px; }
    .invoice-info { text-align: right; }
    .invoice-info p { margin: 3px 0; font-size: 14px; }
    .parties { display: flex; justify-content: space-between; margin: 30px 0; }
    .party { }
    .party h3 { font-size: 12px; color: #666; text-transform: uppercase; margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 30px 0; }
    th { background: #f7fafc; text-align: left; padding: 12px; font-size: 13px; color: #666; border-bottom: 2px solid #e2e8f0; }
    td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
    .total-row { font-weight: 700; font-size: 16px; }
    .total-row td { border-top: 2px solid #4299e1; padding-top: 15px; }
    .status { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; }
    .status.paid { background: #c6f6d5; color: #276749; }
    .status.pending { background: #fefcbf; color: #744210; }
    .status.overdue { background: #fed7d7; color: #9b2c2c; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; color: #666; font-size: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${data.schoolName}</h1>
      <p style="color: #666;">Educational Institution</p>
    </div>
    <div class="invoice-info">
      <h2 style="font-size: 24px;">INVOICE</h2>
      <p><strong>${data.invoiceNumber}</strong></p>
      <p>Issued: ${data.issuedDate}</p>
      <p>Due: ${data.dueDate}</p>
      <p><span class="status ${data.status.toLowerCase()}">${data.status}</span></p>
    </div>
  </div>

  <div class="parties">
    <div class="party">
      <h3>Bill To</h3>
      <p><strong>${data.studentName}</strong></p>
      <p>Student ID: ${data.studentId}</p>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th style="text-align: right;">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${data.items.map((item) => `
        <tr>
          <td>${item.description}</td>
          <td style="text-align: right;">$${item.amount.toFixed(2)}</td>
        </tr>
      `).join("")}
      <tr class="total-row">
        <td>Total</td>
        <td style="text-align: right;">$${data.total.toFixed(2)}</td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    <p>Thank you for choosing ${data.schoolName}</p>
    <p>Generated by EduPlatform - Educational Management System</p>
  </div>
</body>
</html>
  `.trim();
}
